trigger:
  - master

pool:
  name: 'DevOps XM Linux'

stages:
- stage: ContinuosIntegration
  jobs:
    - job: TestAndSscan
      displayName: 'Test and scan'

      steps:
        - script: pip install --upgrade poetry tox
          displayName: 'Install pip'

        - script: |
            curl -sSL https://install.python-poetry.org | python3 -
          displayName: 'Install Poetry'

        - script: |
            echo "##vso[task.prependpath]$HOME/.local/bin"
          displayName: 'Add Poetry to PATH'

        - script: echo $PATH
          displayName: 'Check PATH'

        - script: poetry --version
          displayName: 'Check Poetry Version'

        - script: |
           poetry lock
           poetry install
          displayName: 'Install dependencies with Poetry'
        - task: SonarQubePrepare@5
          displayName: 'Preparing SonarQube scanner'
          inputs:
            SonarQube: 'SC_SONAR_CODEQUALITY'
            scannerMode: 'CLI'
            configMode: 'manual'
            cliProjectKey: 'RP-CND-PlaneacionOperacion-SOLARLIB'
            cliProjectName: 'RP-CND-PlaneacionOperacion-SOLARLIB'
            extraProperties: |
              sonar.exclusions=**/*.bin,**/test_*
              sonar.python.coverage.reportPaths=$(System.DefaultWorkingDirectory)/coverage.xml

        - script: poetry run pytest
          displayName: 'Run Tests'
          continueOnError: true
        
        - task: SonarQubeAnalyze@5
          inputs:
            jdkversion: 'JAVA_HOME_11_X64'
        - task: SonarQubePublish@5
          inputs:
            pollingTimeoutSec: '300'
        - task: sonar-buildbreaker@8
          inputs:
            SonarQube: 'SC_SONAR_CODEQUALITY'