version: '3.5'

services:

  tests:
    build:
      context: ./
      dockerfile: Dockerfile.local
  #   depends_on:
  #     - sonarqube
  # sonarqube:
  #   image: sonarqube:latest
  #   environment:
  #     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  #     - SONARQUBE_JDBC_USERNAME=sonar
  #     - SONARQUBE_JDBC_PASSWORD=sonar
  #   ports:
  #     - "9000:9000"